server:
  port: 8861
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:114.116.0.103}:${MYSQL_PORT:3306}/skylight?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    static-path-pattern: /**

  resources:
    static-locations:  /META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path},file:${web.cover-path}


web:
  upload-path: D:/work/devops/skyLight/skyLight/src/main/resources/static
  cover-path: D:/work/devops/TreeHole/treehole/src/main/resources/static/cover
